polls/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns =[
	path('', views.vote_or_not, name='vote'),
	path('signup/', views.signup, name='signup'),
	path('accounts/', include('django.contrib.auth.urls'), name='accounts'),
	path('logout/', views.logoutin, name='logoutin'),
	path('activate/<uidb64>/<token>/',
        views.activate, name='activate'),
]

vnntu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import home

urlpatterns = [
	path('', home),
    path('admin/', admin.site.urls),
    path('vote/', include('polls.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.

class Positions(models.Model):

	position = models.CharField(max_length=5,
		choices=(
			("PR", "President"),
			("VP", "Vice President"),
			("HG", "Honorary Secretary"),
			("None", "Choose position")
		),
		default="None"
	)

	def __str__(self):
		return self.position

class Applicant(models.Model):
	
	name = models.CharField(max_length=200) 
	year = models.IntegerField(
		choices=(
			(1, '1'),
			(2, '2'),
			(3, '3'),
			(4, '4')
		),
		default=1
	)
	major = models.CharField(max_length=200)

	choices = models.ManyToManyField(Positions, through='Choice')

	image = models.ImageField(upload_to='applicant photos', blank=True)

	def __str__(self):
		return self.name

class Choice(models.Model):

	choice = models.ForeignKey(Positions, on_delete=models.CASCADE)
	applicant = models.ForeignKey(Applicant, on_delete=models.CASCADE)

	number_of_votes = models.IntegerField(default=0)

	number_of_votes_against = models.IntegerField(default=0)

	class Meta:
		ordering = ['choice', '-number_of_votes']

	def __str__(self):
		return self.applicant.name + '__' + self.choice.position + '__' + str(self.number_of_votes)


class Vote(models.Model):

	vote = models.ForeignKey(Choice, on_delete=models.CASCADE)

	voter = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

	vote_time = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.voter.username + '__' + self.vote.choice.__str__()

	class Meta:
		ordering = ['voter', 'vote']
		unique_together = (("vote", "voter"),)




	

polls/forms.py
from django import forms
from django.core.validators import EmailValidator

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def clean_email(self):
        email_form = self.cleaned_data['email']
        print('here5')
        print(email_form)
        if not (email_form.endswith('e.ntu.edu.sg') or email_form.endswith('ntu.edu.sg')):
            print('here6')
            raise forms.ValidationError('Please enter NTU email!')
        try:
        	match = User.objects.get(email=email_form)
        except User.DoesNotExist:
        	return email_form
        raise forms.ValidationError('This email is already registered!')
    

polls/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic

from django.db import IntegrityError

from django.http import HttpResponse

from django.contrib.auth import login, authenticate
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

from django.template.loader import render_to_string

from django.contrib.auth.models import User
from django.contrib.auth.views import logout_then_login
from django.core.mail import EmailMessage


from .models import Positions, Vote, Choice
from .tokens import account_activation_token
from .forms import SignupForm

# Create your views here.

class VoteView(LoginRequiredMixin, generic.ListView):
	model = Positions

	context_object_name = 'positions_list'

	template_name = 'polls/vote.html'

	def get_query_set(self):
		return Positions.objects.all()

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['previous_votes'] = [prev_vote.vote for prev_vote in Vote.objects.filter(voter=self.request.user)]

		return context

	def post(self, request):
		choices = ['choicePR', 'choiceVP', 'choiceHG']
		votes = []
		pos_choices = []

		prev_votes = Vote.objects.filter(voter=request.user)

		try:
			for choice in choices:
				splits = request.POST[choice].split(' ')
				pos_choice = Choice.objects.get(pk=splits[0])
				if len(splits) == 1:
					pos_choice.number_of_votes += 1
				else:
					pos_choice.number_of_votes_against +=1
				pos_choices.append(pos_choice)
				print(pos_choices)
				vote = Vote(vote=pos_choice, voter=request.user)
				votes.append(vote)
				print(votes)

		except IntegrityError:
			return HttpResponse("yey")

		except (KeyError, Choice.DoesNotExist):
			return render(request, self.template_name, {'positions_list': self.get_query_set(),
														'error_message': "Please select a choice for all position"})

		print(choices)
		print(votes)
		for choice in pos_choices:
			choice.save()
		for vote in votes:
			vote.save()

		return render(request, 'polls/voted.html', {'voted': False})


def signup(request):
	if request.method == 'POST':
		form = SignupForm(request.POST)
		if form.is_valid():
			user = form.save(commit=False)
			user.is_active = False
			user.save()
			current_site = get_current_site(request)
			mail_subject = 'Activate your account.'
			message = render_to_string('polls/acc_active_email.html', {
				'user': user,
				'domain': current_site.domain,
				'uid':urlsafe_base64_encode(force_bytes(user.pk)).decode(),
				'token':account_activation_token.make_token(user),
			})
			to_email = form.cleaned_data.get('email')
			email = EmailMessage(
						mail_subject, message, to=[to_email]
			)
			email.send()
			return render(request, 'polls/acc_active.html')
	else:
		form = SignupForm()
	return render(request, 'polls/signup.html', {'form': form})



def activate(request, uidb64, token):
	try:
		uid = force_text(urlsafe_base64_decode(uidb64))
		user = User.objects.get(pk=uid)
	except(TypeError, ValueError, OverflowError, User.DoesNotExist):
		user = None
	if user is not None and account_activation_token.check_token(user, token):
		user.is_active = True
		user.save()
		login(request, user)
		# return redirect('home')
		return render(request, 'polls/acc_success.html')
	else:
		return HttpResponse('Activation link is invalid!')

def logoutin(request):
	return logout_then_login(request)

@login_required
def vote_or_not(request):
	match = Vote.objects.filter(voter=request.user)
	if match:
		return render(request, 'polls/voted.html', {'voted': True})
	else:
		return VoteView.as_view()(request)
	

vnntu/views.py
from django.shortcuts import redirect

def home(request):
	return redirect('vote')

polls/templates/polls/acc_active.html
<head>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"/>
    <style>
        body{
			background: rgb(51, 51, 51);
		}
		#logo{
			margin-left: auto;
			margin-right: auto;
			text-align: center;
			padding-top: 30px;
		}
		#main_head{
			text-align:center;
			font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
			font-size: 50px;
			padding-top: 50px;
			font-weight: 400;
            color: aliceblue;
		}
		.button_vote{
			text-align:center;
		}
        </style>
</head>
<body>
	<div id="logo">
	<img style="width:300px; height:50px" src="http://vnntu.com/wordpress/wp-content/uploads/2015/01/Logo-type.png" alt="">
	</div>
    <h1 id="main_head">Please confirm your email address in your mailbox to complete the registration</h1>

	
</body>

polls/templates/polls/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

polls/templates/polls/acc_success.html
<head>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"/>
    <style>
        body{
			background: rgb(51, 51, 51);
		}
		#logo{
			margin-left: auto;
			margin-right: auto;
			text-align: center;
			padding-top: 30px;
		}
		#main_head{
			text-align:center;
			font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
			font-size: 50px;
			padding-top: 50px;
			font-weight: 400;
            color: aliceblue;
		}
		.button_vote{
			text-align:center;
		}
        </style>
</head>
<body>
	<div id="logo">
	<img style="width:300px; height:50px" src="http://vnntu.com/wordpress/wp-content/uploads/2015/01/Logo-type.png" alt="">
	</div>
    <h1 id="main_head">Activation successful</h1>
    <div class="button_vote">
    	<a role="button" class="btn btn-primary" href="{% url 'vote' %}" > <span> Vote now! </span></a>	
    </div>
	
</body>

polls/templates/polls/signup.html
<head>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"/>
  <style>
  .jumbotron{
    background: rgb(255, 255, 255);
    margin-top: 50px;
    width: 400px;
    height: auto;
    margin-left:auto;
    margin-right: auto;
    border-radius: 12px;
    padding-top: 10px;
  }
  #logo{
      margin-left: auto;
      margin-right: auto;
      text-align: center;
      padding-top: 30px;
    }
    body{
      background: url(https://images.unsplash.com/photo-1464639351491-a172c2aa2911?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80);
      background:cover no-repeat;
    }
    #main_head{
      text-align:center;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
      font-size: 30px;
      padding-bottom: 15px;
      font-weight: 500;
    }
    input{
      
      border-width: 0.5px;
      border-radius: 3px;
      height: 30px;
      width: 300px;
      font-size: 14px;
      outline-offset: 1px;
      padding-left: 5px;
      border-color: rgb(110, 110, 110);
    }
    .form{
      padding-left:50px; 
    }
    label{
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
      font-size: 15px;
      font-weight: 400;
    }
    .btn{
      margin-bottom: 20px;
    }
    .errorlist{
      padding-left: 2px;
      padding-right: 2px;
      font-weight: 300;
    }
  </style>
</head>
{% block content %}
<div id="logo">
  <img style="width:300px; height:50px" src="http://vnntu.com/wordpress/wp-content/uploads/2015/01/Logo-type.png" alt="">
</div>
<div class="jumbotron form-group">
  <h2 id="main_head">Sign up</h2>
  <form class="form" method="post">
    {% csrf_token %}
      {% for field in form %}
      <p>
        {{ field.errors }}
        {{ field.label_tag }}<br>
        {{ field }}
      </p>
      {% endfor %}

    <button class="btn btn-primary" type="submit">Sign up</button>
    <a href="{% url 'login' %}">Log in here</a>
  </form>
</div>
{% endblock %}

polls/templates/polls/vote.html
<!DOCTYPE html>
<html>
<head>
	<title>Vote</title>
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"/>
	<style>
		body{
			background: url(https://images.unsplash.com/photo-1464639351491-a172c2aa2911?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80);
			background:cover no-repeat;
		}
		#logo{
			margin-left: auto;
			margin-right: auto;
			text-align: center;
			padding-top: 30px;
		}
		.jumbotron{
			background: rgb(255, 255, 255);
			margin-top: 50px;
			width: 700px;
			height: auto;
			margin-left:auto;
			margin-right: auto;
			border-radius: 12px;
			padding-top: 10px;
		}
		.btn{
			margin-bottom: 10px;
			margin-left: 220px;
			width: 100px;
		}
		.form{
			padding-left:50px; 
			margin-top: 20px;
		}
		li{
			font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
			font-size: 18px;
			font-weight: 650;
			margin-top:10px;
		}
		label{
			font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
			font-size: 16px;
			font-weight: 400;
			color: #666;
     		cursor: pointer;
		}
		.img_app{
			margin-left: 10px;
			margin-top: 30px;
		}
		.form-radio
			{
				-webkit-appearance: none;
				-moz-appearance: none;
				appearance: none;
				display: inline-block;
				position: relative;
				background-color: #f1f1f1;
				color: rgb(75, 75, 75);
				top: 10px;
				height: 28px;
				width: 28px;
				border: 0;
				border-radius: 50px;
				cursor: pointer;     
				margin-right: 7px;
				outline: none;
			}
			.form-radio:checked::before
			{
				position: absolute;
				font: 13px/1 'Open Sans', sans-serif;
				left: 11px;
				top: 7px;
				content: '\02143';
				transform: rotate(40deg);
			}
			.form-radio:hover
			{
				background-color: #f7f7f7;
			}
			.form-radio:checked
			{
				background-color: #f1f1f1;
			}

	</style>
</head>
<body>
	<div id="logo">
		<img style="width:300px; height:50px" src="http://vnntu.com/wordpress/wp-content/uploads/2015/01/Logo-type.png" alt="">
	</div>
	{% if positions_list %}
	<div class="jumbotron">
	<form class="form form-group" method="post">
		{% csrf_token %}
			{% if error_message %}
			<strong> {{ error_message }} </strong>
			{% endif %}
		<ul style="list-style: none;">
			{% for position in positions_list %}
				{% for choice in position.choice_set.all %}
				<li>{{ position.get_position_display }}: {{ choice.applicant.name }}: {{choice.applicant.major}}/{{choice.applicant.year}} <img class="img_app"src="{{ choice.applicant.image.url }}" width="200"><br></li>
				<table>
					<tr>
						<td><input class="form-radio" type="radio" name="choice{{position.position}}" id = "choice{{forloop.counter}}" value = "{{choice.id}}">
							<label for="choice{{forloop.counter}}">Yay</label>
						</td>
					</tr>
					<tr>
						<td>	
							<input class="form-radio" type="radio" name="choice{{position.position}}" id = "choice{{forloop.counter}}none" value = "{{choice.id}} !">
							<label for="choice{{forloop.counter}}none">Nay</label><br><br>
						</td>
					</tr>
				</table>
				{% endfor %}
			{% endfor %}
			</ul>
		<button class="btn btn-primary center-block" type="submit">Vote!</button>
		<a class="btn btn-default" href="{% url 'logoutin' %}" >Logout</a>
	</form>
	</div>
	{% else %}
	No vote

	{% endif %}

</body>
</html>

polls/templates/polls/voted.html
<head>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"/>
    <style>
        body{
			background: rgb(51, 51, 51);
		}
		#logo{
			margin-left: auto;
			margin-right: auto;
			text-align: center;
			padding-top: 30px;
		}
		#main_head{
			text-align:center;
			font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
			font-size: 50px;
			padding-top: 50px;
			font-weight: 400;
            color: aliceblue;
		}
		#button_logout{
			 position: absolute;
    		top: 10px;
    		right: 10px;
		}
        </style>
</head>
<body>
	<div id="logo">
	<img style="width:300px; height:50px" src="http://vnntu.com/wordpress/wp-content/uploads/2015/01/Logo-type.png" alt="">
	</div>
	{% if voted %}
    <h1 id="main_head">You already voted!</h1>
	{% else %}
	<h1 id="main_head">Thank you for your vote!</h1>
	{% endif %}
	<a id="button_logout" class="btn btn-default" href="{% url 'logoutin' %}" >Logout</a>
</body>